languageCode = "es-ES"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
[pagination]
pagerSize = 10

# not pluralize title pages by default
pluralizelisttitles = false

[params]
viewMorePostLink = "/noticias/"
author = "Renault España"
defaultKeywords = ["vehiculos", "renault"]
mainSections = ["blog"]
defaultDescription = ""

# Social media
facebook_site = ""
twitter_site = ""
default_sharing_image = ""

# Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
enableGoogleMaps = true
googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

latitude = "-12.043333"
longitude = "-77.028333"

# Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
style = "marsala"

# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 50 emails each month for free.
#
# What you need to do for the setup?
#
# - register your account to https://formspree.io/register
# - login and create new form
# - set your form's endpoint url under 'formspree_action' below
# - upload the generated site to your server
# - test a dummy email yourself
# - you're done. Happy mailing!
#
# Enable the contact form by entering your Formspree.io endpoint url
formspree_action = "https://formspree.io/sample/of/endpoint"
contact_form_ajax = false

# Formspree form supports Google reCAPTCHA Key (type v2).
# If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
#
# By default, Formspree use a redirect page for recaptcha widget.
# If you use a recaptcha widget in your contact page, you should do next steps.
# (if you don't want, skip these steps)
#
#   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
#   2. select reCAPTCHA v2 and checkbox widget type.
#   3. remember site key and secret key.
#   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
#   5. change `enableRecaptchaInContactForm` is to true
#   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
#
enableRecaptchaInContactForm = false
googleRecaptchaKey = "site_key_for_google_recaptcha"

# Format dates with Go's time formatting
date_format = "January 2, 2006"

dropdown_mouse_over = false

# Enable and disable widgets for the right sidebar
[params.widgets]
categories = true
tags = true
search = true

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.servicios]
enable = true
title = "SERVICIOS DISPONIBLES"
cols = 3

[params.promociones]
enable = true
title = "PROMOCIONES DISPONIBLES"
cols = 3

[params.clients]
title = "NUESTROS CLIENTES"
subtitle = ""

[params.list_cars]
title = "VEHÍCULOS DISPONIBLES"
hide_summary = false

[params.recent_posts]
enable = true
title = "Noticias"
subtitle = "Últimas noticias y novedades"
hide_summary = false
